### PR TITLE
Added Item sell-limits

### PR DESCRIPTION
**Pull request by Dietrich-io**
Added the possibility to limit items the store will buy!

Limit as many Items as you want by adding:
```
LimitedItems = { 
            {itemName="apple", amount=10}  
}
```

This is not necassary, so you wont be forced to add this to any store. Just add if you want to limit the item amount that the store will accept until next restart.

Also added a new line for each language if limit is reached.

### CODE REVIEW

**Comment by Dietrich-io** [comment]
Maybe you have to translate the english version more likely into: "I do not buy that amount of this item" or something like that. Not that good in translating perfectly :)

**Comment by outsider31000** [comment]
of what i understood  is if item exists in configitems to buy  then set an ammount that can be sold per server restart ?

**Comment by outsider31000** [comment]
if not added  or not found then buy  normally ?

**Comment by outsider31000** [comment]
and please add the lines to all stores not just one. and leave them commented with -- and just say delete if you dont want item to be sold with a limit per restart

**Comment by outsider31000** [comment]
also use the vorp guied lines when making pull requests . we dont use table.insert or ~= nil  unless you need false or true , an if statment already does that.
thanks for the feature .

**Comment by Dietrich-io** [comment]
It's the items in SellItems, so you can balance your server economy.

So for example:
The player want to sell goldnuggets to any store. The serverowner can limit the accepted amount one store is buying from the player.
If the item to be sold isnt in LimitedItems or LimitedItems dont even exists then all works normally with no limitations :)
For a future update i am thinking about adding an attribute which let you make both but not for now, since this was the important feature to control the server economy.

**Comment by outsider31000** [comment]
Understood  yes. Would be great to do the same for buy items per restart.

**Comment by Dietrich-io** [comment]
Will get to it as soon as possible

**Pull request merged**
